### ISSUE TITLE
In Object Diagrams, make it impossible to add fields nodes that are not a child of an object node

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#39] opened 2015-02-07 13:50 UTC
This behavior is already implemented for CallNodes in the sequence diagams.

**Comment by JoelChev** [comment] 2015-02-08 03:46
@prmr I have addressed the bug; it is now impossible to add Field Nodes unless they are added into Object Nodes. I have noticed a persistent bug however (it was present even before the update and I have tried to solve it but to no avail).

Steps to reproduce:
1. Use the lasso to select an Object Node with a Field Node inside it.
2. Try to move the selection around. The Field Node becomes temporarily "unhooked" from the Object Node and wiggles around in space while you move. It snaps back into place on release of the mouse.

I have tried looking into Violet 0.23 and into the behaviour of Call Nodes+ImplicitParameter Nodes to find an idea of why the above bug is ocurring, but I can't figure out what the issue is.

**Comment by prmr** [comment] 2015-02-08 04:15
Good catch, this issue is caused by the translation being done twice for children nodes. 

In `GraphPanelMouseMotionListener`, you'll notice that the code goes through the entire selection and does `n.translate(dx, dy);`.

However, the selection includes a parent node and all its children. However, if you look at the code for `translate` it dynamically dispatches to `AbstractNode.translate`:
```
public void translate(double pDeltaX, double pDeltaY)
	{
		for(Node node : aChildren)
		{	
			node.translate(pDeltaX, pDeltaY);
		}
	}
```
which goes through all the children (again!) so basically the error is caused by the children nodes being translated twice. Note that the same thing happens in sequence diagrams.
Please create a new issue for this and copy this information into it. Whoever has time can tackle it, either for 0.2 or 0.3.

**Comment by JoelChev** [comment] 2015-02-08 18:44
@prmr, Alright, I started issue #42 to address the translating bug, which I will tackle today. Can you or @EJBQ please check out this branch and ensure that adding Field Nodes is behaving as desired? If so, I think we can close this issue and I can merge this branch into master. Thanks!

**Comment by prmr** [comment] 2015-02-08 18:47
It looks to me like it's doing the right thing.

**Comment by JoelChev** [comment] 2015-02-08 19:27
Alright, I just merged this into the master branch and pushed it. I will close this now.

**Closed by JoelChev** 2015-02-08 19:27 UTC
Labels: enhancement, logic

**Comment by EJBQ** [comment] 2015-02-08 19:45
It seems to work fine for me as well. The only thing I noticed, which doesn't seem to be caused by this change, is that it's not possible to move a Field Node from one Object to another. Is that a feature we want available?

**Comment by prmr** [comment] 2015-02-08 19:46
I don't think so, at least in the short term (I don't remember ever wanting this feature).
