### ISSUE TITLE
Could not find or load main class ca.mcgill.cs.jetuml.UMLEditor

### ISSUE THREAD

**Issue by jidicula** [prmr/JetUML#336] opened 2020-02-07 22:54 UTC
**Description**
Attempting to run from Terminal following installation instructions to run:
`$ java -jar JetUML-2.5.jar` gives the error:

`Error: Could not find or load main class ca.mcgill.cs.jetuml.UMLEditor`

**Steps to reproduce**
1. Download .jar file.
2. Run `$ java -jar JetUML-2.5.jar` in the directory where the .jar file was saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/12765385/74071714-ae08e600-49d2-11ea-93cb-b0860cb8f42d.png)

**Configuration**
 - JetUML Release: 2.5
 - OS + version: macOS 10.15.3
 - Java version: openjdk version "1.8.0_202"

**Comment by prmr** [comment] 2020-02-07 22:59
I can't reproduce this on Windows. @cc-21 do you mind trying this out on your mac?

**Comment by jidicula** [comment] 2020-02-07 23:02
Thanks for the quick reply. I suspect it's a classpath issue but I'm not sure how to resolve it.

**Comment by prmr** [comment] 2020-02-07 23:10
@jidicula  can you put this somewhere and try `java -jar test.zip`? This is the simplest possible executable jar.
[test.zip](https://github.com/prmr/JetUML/files/4173268/test.zip)

**Comment by jidicula** [comment] 2020-02-07 23:11
Yep, got `Success` as the output:
![image](https://user-images.githubusercontent.com/12765385/74072591-41431b00-49d5-11ea-90cc-3b9f7c176529.png)

**Comment by prmr** [comment] 2020-02-07 23:18
Interesting. Probably a dependency problem. Could you please try again: 
[test.zip](https://github.com/prmr/JetUML/files/4173297/test.zip)

**Comment by jidicula** [comment] 2020-02-07 23:30
Got the output `Error: Could not find or load main class a.Test`

![image](https://user-images.githubusercontent.com/12765385/74073297-de9f4e80-49d7-11ea-9f7e-1dcae4c9dd74.png)

**Comment by prmr** [comment] 2020-02-07 23:34
OK thanks. The issue most likely that your JRE does not have the JavaFX binaries. I'll be closing this since it's a Java config problem and not a JetUML issue. To fix the problem, make sure your have openjfx installed and on the classpath. Also FYI, Release 3.0 is coming out soon and with it we'll be distributing JetUML as a fat jar precisely to avoid these kinds of issues.

**Closed by prmr** 2020-02-07 23:34 UTC

**Comment by jidicula** [comment] 2020-02-07 23:37
Great, thanks!
